### ISSUE TITLE
이미지 크롭 모듈 구현

### ISSUE THREAD

**Issue by Jinviz** [ray9583/SeeLook#18]
## Description
- 업로드 이미지의 다양한 해상도로 인한 일정하지 못한 구조의 View영역 확인하였음. 일정한 해상도 이미지 렌더링을 위해,  이미지 크롭 기술 구현할 것임.

## To-do
- [x] API 요청 영역 구현 
- [x] useImageCrop hook 구현
- [x] 크롭 View 영역 스타일링

## Expected time
- ~06-05

## ETC
API 부적합으로 인한 실패 가능성 존재함
