### ISSUE TITLE
이미지 백그라운드 제거 모듈 구현

### ISSUE THREAD

**Issue by Jinviz** [ray9583/SeeLook#19]
## Description
- 단조로운 느낌의 앨범 View를 구현하기 위해, 이미지의 배경을 제거하는(Background removal) 변환 hooks을 구현할 것임.
- 
## To-do
- [x] useBgRemoval hook 구현
- [x] 사라진 배경을 랜덤한 HEX값 컬러 영역으로 대체
- [x] 가공된 이미지를 Stroage에 저장 구현

## Expected time
- ~06-05 => ~06-06

## ETC
API 부적합으로 인한 실패 가능성 존재함

**Comment by Jinviz** [comment]
- API 서버 닫은듯
 - 또한, 모든 백그라운드 제거 API는 유료 서비스
