### ISSUE TITLE
카테고리 전체 또는 미선택 시 모든 이미지 출력

### ISSUE THREAD

**Issue by minggichae** [ray9583/SeeLook#22]
## Description
- lookbook 페이지에서 카테고리를 선택하지 않거나, 전체를 선택한 경우 모든 이미지를 불러와야함.
 폴더 내의 이미지를 가져오는 것을 구현해야함.

## To-do
- [x] 카테고리를 선택하지 않은 "전체" 버튼 만들기 (카테고리 선택을 한 후 돌아가는 기능도 포함하기 위함)
- [x] 선택하지 않은 경우 모든 이미지 불러오기
- [x] 이미지 데이터의 날짜 정보를 가져와 최신순으로 정렬하기

## Expected time
- ~06-06
