### ISSUE TITLE
Layout css 및 반응형 페이지 로직 구현

### ISSUE THREAD

**Issue by jihoon135** [ray9583/SeeLook#26]
## Description
- Layout css 및 반응형 페이지 로직 구현

## To-do
- [x] Layout background로 오게 하기
- [ ] 각 컴포넌트 div 비율 조정
- [x] 반응형 페이지 로직 추

## Expected time
- ~06-07

## ETC
- 각 컴포넌트 div 비율 조정은 원활하지 않을 수 있음.
