### ISSUE TITLE
이미지 업로드, 룩북 페이지 수정 요구 사항

### ISSUE THREAD

**Issue by jihoon135** [ray9583/SeeLook#33]
## Description
- 업로드 페이지 에러 분기 처리가 필요함. 사진 업로드 시, 온도 혹은 이미지 등 필요한 정보들이 담겨 있지 않으면 업로드가 안되게 하고, toast 메시지를 이용하여 사용자에게 업로드 여부 전달
- 나의 룩북 이미지 크기 균일하게 업로드 되도록 수정
- 나의 룩북 페이지에서 메인 페이지로 이동할 수 있는 버튼 추가
- 메인, 이미지 업로드, 룩북 확인 페이지 CSS 조정. Login css에 맞춰서 수정 하는 것이 좋아보이긴 하는데, 회의가 필요할 것 같습니다.

## To-do
- [x] 업로드 페이지 에러 분기 처리
- [x] 업로드 된 이미지 크기 균일하게 처리 
- [x] 나의 룩북 페이지에서 메인 페이지로 이동 하는 버튼 추가
- [x] 메인, 이미지 업로드, 룩북 확인 페이지 CSS 조정

## Expected time
- ~06-08

## ETC
- 수정 요구 사항이긴한데, 가능한 사람이 수정 하는 걸로 할게요!

**Comment by Jinviz** [comment]
Checked it

**Comment by minggichae** [comment]
제가 업로드 페이지 에러 분기 처리와 업로드 된 이미지 크기 균일하게 처리 진행 중에 있습니다.

**Comment by jihoon135** [comment]
CSS쪽 테스트 해보고 있겠습니다
