### ISSUE TITLE
오늘의 룩북 추천 기능

### ISSUE THREAD

**Issue by minggichae** [ray9583/SeeLook#37]
## Description
- 룩북 페이지에서 오늘의 룩북 추천 버튼을 눌러 온도를 입력하면 일정 오차 범위 내의 사진을 띄워야함. 룩북 추천 버튼을 만들고, 팝업창을 통해 작업을 수행해야함. 추가로 모달 컴포넌트를 따로 만들어서 진행 할 예정.

## To-do
- [x] 오늘의 룩북 추천 버튼 만들기
- [x] 팝업창을 띄워 온도를 입력받기
- [x] 입력 받은 온도 +-2도를 기준으로 이미지의 메타데이터 온도와 비교하여 이미지 노출 시키기
- [x] 팝업창 스타일링 하기

## Expected time
- ~06-09

## ETC
-

**Comment by minggichae** [comment]
팝업창에 대해 찾아보며 Modal이라는 라이브러리를 찾게 되었다.
부모 컴포넌트인 Photo에서 자식 컴포넌트인 LookBookModal 컴포넌트에 props를 전달하여 코드의 가독성을 높였다.
