### ISSUE TITLE
비전업 최종 결과 보고서 작성

### ISSUE THREAD

**Issue by minggichae** [ray9583/SeeLook#41]
## Description
- 비전업에 제출 할 보고서 작성이 필요함. 활동일지, 주차별 활동 내용, 개인별 최종 보고서, 팀별 최종 보고서를 작성을 진행할 예정

## To-do
- [x] 활동일지
- [x] 주차별 활동 내용
- [x] 개인별 최종 보고서
- [x] 팀별 최종 보고서

## Expected time
- ~06-11

## ETC
- 개인별 최종 보고서는 틀을 제공 할 예정이오니 자세한 내용은 개인이 직접 기입 하시길 바랍니다.
